services:
  adrianvillanueva:
    image: ghcr.io/adrianvillanueva997/cv:latest

    networks:
      - proxy

    ports:
      - target: 80
        mode: ingress

    labels:
      - traefik.enable=true
      - traefik.http.middlewares.cv-redirect-https.redirectscheme.scheme=https
      - traefik.http.middlewares.cv-redirect-https.redirectscheme.permanent=true
      - traefik.http.routers.cv-http.middlewares=cv-redirect-https
      - traefik.http.routers.cv-http.rule=Host(`resume.adrianvillanueva.com`)
      - traefik.http.routers.cv-http.entrypoints=http
      - traefik.http.routers.cv-https.rule=Host(`resume.adrianvillanueva.com`)
      - traefik.http.routers.cv-https.middlewares=error-pages-middleware
      - traefik.http.routers.cv-https.tls.certresolver=letsencrypt
      - traefik.http.routers.cv-https.tls=true
      - traefik.http.routers.cv-https.entrypoints=https
      - "traefik.http.services.cv.loadbalancer.server.port=80"
      - traefik.docker.network=proxy

    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s

networks:
  proxy:
    external: true
